version: '3.4'
services:
  mongodb:
    image: mongo:latest
    ports: 
    - "27017:27017"
    container_name: mongodb 
  mongodb_seed:
    build: services/database/mongodb_seed
    links:
    - mongodb
