version: '3'
services:
  tomcat:
    build: my-rest-api
    security_opt:
    - apparmor:unconfined
    hostname: localhost 
    ports:
    - "8080"
    volumes:
    - ./my-rest-api/logs/:/usr/local/tomcat/logs
