version: '3.4'
services:
  mongodb:
    image: mongo:latest
    ports: 
    - "27017:27017"
    environment:
    # provide your credentials here
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root
    container_name: mongodb 
  mongodb_seed:
    build: services/database/mongodb_seed
    links:
    - mongodb
