version: '3'
services:
  tomcat:
    build: my-rest-api
    security_opt:
    - apparmor:unconfined
    ports:
    - "8080:8080"
    volumes:
    - ./my-rest-api/logs/:/usr/local/tomcat/logs
  mongo:
    build: mongo
    ports:
    - "27017:27017"
