version: '3.4'
services:
  mongodb:
    image: mongo:latest
    ports: 
    - "27017:27017"
    environment:
    # provide your credentials here
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root
    container_name: mongodb
    networks:
    - mongo   
  mongodb_seed:
    build: services/database/mongodb_seed
    networks:
    - mongo
    depends_on:
    - mongodb
networks:
    mongo:
        driver: bridge

